# Generated by Django 6.0.7 on 2026-07-27 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms_documents', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('storage_backend', models.CharField(default='LOCAL', max_length=20)),
                ('storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('storage_state', models.CharField(choices=[('PENDING', 'Pending'), ('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('AVAILABLE', 'Available'), ('CORRUPTED', 'Corrupted'), ('QUARANTINED', 'Quarantined'), ('ARCHIVED', 'Archived')], default='UPLOADING', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dms_documents.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dms_document_versions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'version'), name='unique_version_per_document')],
            },
        ),
    ]
