# Generated by Django 6.0.7 on 2026-07-29 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('redirect_uris', models.TextField()),
                ('grant_types', models.TextField()),
                ('response_types', models.TextField()),
                ('scope', models.TextField(default='')),
                ('is_confidential', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_clients', to='tenants.tenant')),
            ],
            options={
                'db_table': 'iam_oauth_clients',
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=255)),
                ('redirect_uri', models.URLField(max_length=2048)),
                ('scope', models.TextField(default='')),
                ('code_challenge', models.CharField(blank=True, max_length=255, null=True)),
                ('code_challenge_method', models.CharField(blank=True, max_length=10, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='tenants.tenant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='iam_oauth.oauth2client')),
            ],
            options={
                'db_table': 'iam_oauth_authorization_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuth2RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.UUIDField()),
                ('token', models.CharField(max_length=255, unique=True)),
                ('scope', models.TextField(default='')),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='iam_oauth.oauth2client')),
                ('replaced_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='iam_oauth.oauth2refreshtoken')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_refresh_tokens', to='tenants.tenant')),
            ],
            options={
                'db_table': 'iam_oauth_refresh_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='oauth2client',
            constraint=models.UniqueConstraint(fields=('tenant', 'client_id'), name='unique_client_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='authorizationcode',
            index=models.Index(fields=['code'], name='idx_auth_code_code'),
        ),
        migrations.AddIndex(
            model_name='authorizationcode',
            index=models.Index(fields=['client', 'is_consumed'], name='idx_auth_code_client_consumed'),
        ),
        migrations.AddConstraint(
            model_name='authorizationcode',
            constraint=models.UniqueConstraint(fields=('client', 'code'), name='unique_auth_code_per_client'),
        ),
        migrations.AddIndex(
            model_name='oauth2refreshtoken',
            index=models.Index(fields=['token'], name='idx_oauth_refresh_token_token'),
        ),
        migrations.AddIndex(
            model_name='oauth2refreshtoken',
            index=models.Index(fields=['client', 'is_revoked'], name='idx_oauth_refresh_token_client_revoked'),
        ),
        migrations.AddIndex(
            model_name='oauth2refreshtoken',
            index=models.Index(fields=['user_id', 'is_revoked'], name='idx_oauth_refresh_token_user_revoked'),
        ),
    ]
