# Generated by Django 6.0.7 on 2026-07-28 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('extension', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('UPLOAD_REQUESTED', 'Upload Requested'), ('UPLOADING', 'Uploading'), ('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('DOCUMENT_CREATED', 'Document Created'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('QUARANTINED', 'Quarantined')], default='NEW', max_length=20)),
                ('storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dms_ingestion_upload_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
