# Generated by Django 6.0.7 on 2026-07-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrole',
            name='permissions',
            field=models.JSONField(default=dict),
        ),
    ]
