# Generated by Django 6.0.7 on 2026-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_permissions_to_tenantrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrole',
            name='kind',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
