# Generated by Django 6.0.7 on 2026-07-18 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam_users', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenantAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attributes', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_attributes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iam_users_tenant_attributes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant', 'attribute'), name='unique_user_tenant_attribute')],
            },
        ),
    ]
