# Generated by Django 6.0.7 on 2026-07-27 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('error', models.TextField()),
                ('retries', models.PositiveIntegerField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_eventbus_dead_letter_event',
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['event_type'], name='idx_dlq_event_type'), models.Index(fields=['tenant_id'], name='idx_dlq_tenant_id')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_eventbus_processed_event',
                'indexes': [models.Index(fields=['message_id'], name='idx_processed_event_message_id')],
            },
        ),
    ]
