# Generated by Django 6.0.7 on 2026-07-28 12:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dms_document_types', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('TEXT', 'Text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATE', 'Date'), ('DATETIME', 'DateTime'), ('TIME', 'Time'), ('UUID', 'UUID'), ('EMAIL', 'Email'), ('URL', 'URL'), ('JSON', 'JSON'), ('ENUM', 'Enum')], db_index=True, max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=False)),
                ('filterable', models.BooleanField(default=False)),
                ('sortable', models.BooleanField(default=False)),
                ('indexed', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('validation_rules', models.JSONField(blank=True, null=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_definitions', to='dms_document_types.documenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dms_metadata_definitions',
                'indexes': [models.Index(fields=['tenant', 'document_type'], name='dms_metadat_tenant__f11c59_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'document_type', 'code'), name='unique_metadata_definition_per_tenant_and_document_type')],
            },
        ),
    ]
