# Generated by Django 6.0.7 on 2026-07-14 17:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=255)),
                ('target_id', models.UUIDField()),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='idx_audit_tenant_time'), models.Index(fields=['target_type', 'target_id'], name='idx_audit_target')],
            },
        ),
    ]
